package com.crapp.ui.insights

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.coerceAtLeast
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.crapp.data.insights.Insight
import com.crapp.data.insights.InsightSeries
import com.crapp.data.insights.InsightSeverity
import com.crapp.data.insights.SeriesKind
import com.crapp.data.insights.SeriesPoint

/**
 * Displays an [com.crapp.data.insights.InsightsReport] uploaded from a JSON file --
 * see the `crapp-insights` Claude skill (`.claude/skills/crapp-insights/SKILL.md`),
 * which produces that file from the app's own CSV export.
 * docs/development-plan.md Phase 8 ("CSV export -> Claude analysis skill -> in-app
 * dashboard upload", promoted from future-features.md).
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun InsightsScreen(
    onBack: () -> Unit,
    viewModel: InsightsViewModel = viewModel()
) {
    val uiState by viewModel.uiState.collectAsState()
    val uploadLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.OpenDocument()
    ) { uri -> uri?.let(viewModel::loadFrom) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Insights") },
                navigationIcon = { TextButton(onClick = onBack) { Text("← Back") } }
            )
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .padding(innerPadding)
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(20.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Text(
                "Upload a report generated by the crapp-insights Claude skill from an " +
                    "exported CSV (see Export): trends, frequency, and possible correlations, " +
                    "computed outside the app.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )

            Button(
                onClick = { uploadLauncher.launch(arrayOf("application/json")) },
                enabled = !uiState.isLoading,
                modifier = Modifier.fillMaxWidth()
            ) {
                Text(if (uiState.isLoading) "Loading…" else "Upload Report")
            }

            uiState.error?.let { error ->
                Text(error, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.error)
            }

            val report = uiState.report
            if (report == null) {
                Text(
                    "No report loaded yet.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            } else {
                report.generatedAt?.let {
                    Text("Generated $it", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
                report.summary?.let { summary ->
                    Card(modifier = Modifier.fillMaxWidth()) {
                        Text(summary, modifier = Modifier.padding(16.dp), style = MaterialTheme.typography.bodyMedium)
                    }
                }
                report.insights.forEach { insight -> InsightCard(insight) }
                report.series.forEach { series -> SeriesCard(series) }
            }
        }
    }
}

@Composable
private fun InsightCard(insight: Insight) {
    val accent = if (insight.severity == InsightSeverity.NOTABLE) {
        MaterialTheme.colorScheme.error
    } else {
        MaterialTheme.colorScheme.primary
    }
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
            Text(insight.title, style = MaterialTheme.typography.titleSmall, color = accent)
            if (insight.detail.isNotBlank()) {
                Text(insight.detail, style = MaterialTheme.typography.bodyMedium)
            }
        }
    }
}

@Composable
private fun SeriesCard(series: InsightSeries) {
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            Text(
                series.label + (series.unit?.let { " ($it)" } ?: ""),
                style = MaterialTheme.typography.titleMedium
            )
            if (series.points.isEmpty()) {
                Text("No data points.", style = MaterialTheme.typography.bodyMedium)
            } else {
                when (series.kind) {
                    SeriesKind.LINE -> GenericLineChart(series.points)
                    SeriesKind.BAR -> GenericBarChart(series.points)
                }
            }
        }
    }
}

@Composable
private fun GenericLineChart(points: List<SeriesPoint>) {
    if (points.size < 2) {
        val only = points.firstOrNull()
        Text(
            if (only != null) "${only.date}: ${formatValue(only.value)}" else "No data.",
            style = MaterialTheme.typography.bodyMedium
        )
        return
    }

    val lineColor = MaterialTheme.colorScheme.primary
    val gridColor = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.2f)
    val labelColor = MaterialTheme.colorScheme.onSurfaceVariant
    val minValue = points.minOf { it.value }
    val maxValue = points.maxOf { it.value }
    val range = (maxValue - minValue).let { if (it == 0f) 1f else it }
    val chartHeight = 120.dp

    Column {
        Canvas(
            modifier = Modifier
                .fillMaxWidth()
                .height(chartHeight)
        ) {
            val stepX = size.width / (points.size - 1)
            fun yFor(value: Float): Float = size.height - ((value - minValue) / range) * size.height

            drawLine(gridColor, Offset(0f, 0f), Offset(size.width, 0f), strokeWidth = 1.dp.toPx())
            drawLine(gridColor, Offset(0f, size.height), Offset(size.width, size.height), strokeWidth = 1.dp.toPx())

            val path = Path()
            points.forEachIndexed { index, point ->
                val x = index * stepX
                val y = yFor(point.value)
                if (index == 0) path.moveTo(x, y) else path.lineTo(x, y)
            }
            drawPath(path, color = lineColor, style = Stroke(width = 2.dp.toPx(), cap = StrokeCap.Round, join = StrokeJoin.Round))

            points.forEachIndexed { index, point ->
                val x = index * stepX
                val y = yFor(point.value)
                drawCircle(color = lineColor, radius = 4.dp.toPx(), center = Offset(x, y))
            }
        }
        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
            Text(points.first().date, style = MaterialTheme.typography.labelSmall, color = labelColor)
            Text(points.last().date, style = MaterialTheme.typography.labelSmall, color = labelColor)
        }
    }
}

@Composable
private fun GenericBarChart(points: List<SeriesPoint>) {
    val barColor = MaterialTheme.colorScheme.primary
    val labelColor = MaterialTheme.colorScheme.onSurfaceVariant
    val maxValue = (points.maxOfOrNull { it.value } ?: 0f).let { if (it <= 0f) 1f else it }
    val chartHeight = 96.dp
    val barWidth = 28.dp

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .horizontalScroll(rememberScrollState()),
        horizontalArrangement = Arrangement.spacedBy(10.dp)
    ) {
        points.forEach { point ->
            val barHeight = (chartHeight * (point.value / maxValue)).coerceAtLeast(3.dp)
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.Bottom,
                modifier = Modifier.height(chartHeight + 40.dp)
            ) {
                Text(formatValue(point.value), style = MaterialTheme.typography.labelSmall, color = labelColor)
                Box(
                    modifier = Modifier
                        .width(barWidth)
                        .height(barHeight)
                        .clip(RoundedCornerShape(topStart = 4.dp, topEnd = 4.dp))
                        .background(barColor)
                )
                Spacer(Modifier.height(4.dp))
                Text(
                    point.date,
                    style = MaterialTheme.typography.labelSmall,
                    color = labelColor,
                    textAlign = TextAlign.Center,
                    modifier = Modifier.width(barWidth + 20.dp)
                )
            }
        }
    }
}

private fun formatValue(value: Float): String =
    if (value == value.toLong().toFloat()) value.toLong().toString() else value.toString()
